name: quit_app
description: A minimalist quit smoking app using Urge Surfing.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  intl: ^0.18.0
  uuid: ^4.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/quotes.json
    - assets/data/facts.json

flutter_launcher_icons:
  android: true 
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"